ASCIIDOC_SILENT = $(ASCIIDOC_SILENT_$(V))
ASCIIDOC_SILENT_ = $(ASCIIDOC_SILENT_$(AM_DEFAULT_VERBOSITY))
ASCIIDOC_SILENT_0 = @echo ASCIIDOC $@;

XMLTO_SILENT = $(XMLTO_SILENT_$(V))
XMLTO_SILENT_ = $(XMLTO_SILENT_$(AM_DEFAULT_VERBOSITY))
XMLTO_SILENT_0 = @echo "  XMLTO " $@;
