#!/bin/bash

DEF_VER=2.0.1

if test -d .git -o -f .git
then
    VN=$(git describe --tags --match "[0-9]*" --abbrev=4 HEAD 2>/dev/null)
    git update-index -q --refresh
    test -z "$(git diff-index --name-only HEAD --)" || VN="$VN-dirty"
    VN=$(echo "$VN" | sed -e 's/-/./g');
else
    VN="$DEF_VER"
fi

sed -e "s/@@ABRT_VERSION@@/$VN/g" < abrt.spec.in > abrt.spec

echo -n $VN
