#!/usr/bin/python2

import sys
import subprocess
from abrtcli.cli import main

if __name__ == '__main__':
    # call ourselves again in case of no subcommand
    # and display oneline list
    if len(sys.argv) == 1:
        subprocess.call('{0} list --pretty oneline'.format(sys.argv[0]),
                        shell=True)
        sys.exit(0)

    main()
else:
    raise NotImplementedError
