#!/bin/bash

which nosetests-3 &> /dev/null
if [ $? -ne 0 ]; then
    echo 'python3-nose package required'
    exit 1
fi

nosetests-3 --with-coverage --cover-package=abrtcli --nocapture --no-skip --verbose tests/*.py
