.TH abrt\-cli "1" "12 Oct 2009" ""
.SH NAME
abrt\-cli \- a command line interface to abrt
.SH SYNOPSIS
.B abrt\-cli
[option]
.SH DESCRIPTION
.I abrt\-cli
is a command line tool that manages application crashes catched by
.I abrtd
daemon. It enables access to problem data, and allows to report
problems depending on active abrt plugins.
.SH OPTIONS
.B Basic startup options
.IP "\-V, \-\-version"
Displays version of abrt\-cli.
.IP "\-?, \-\-help"
Print a help message describing all of abrt-cli’s command-line options.

.PP
.B Crash action options
.IP "\-l, \-\-list"
Prints list of crashes which are not reported yet.
.IP "\-r, \-\-report \fIDUMPDIR\fR"
Creates a crash report and then the text editor is invoked on that
report. When you are done with editing the report just exit the editor
and then you will be asked if you want to send the report.
.IP "\-d, \-\-delete \fIDUMPDIR\fR"
Removes data about particular crash.
.IP "\-i, \-\-info \fIDUMPDIR\fR"
Prints detailed information about particular crash.

.PP
.B Listing options
.IP "\-f, \-\-full"
List all crashes, including already reported.

.PP
.B Report options
.IP "\-y, \-\-always"
Creates and sends the crash report automatically, without asking
any questions.

.PP
.B Info options
.IP "\-b, \-\-backtrace"
Includes the crash backtrace in the info output if the backtrace is
available.

.SH ENVIRONMENT VARIABLES
The editor used to edit the crash report is chosen from the
ABRT_EDITOR environment variable, the VISUAL environment variable, or
the EDITOR environment variable, in that order.

.SH SEE ALSO
.IR abrtd (8),
.IR abrt.conf (5),
.IR abrt-plugins (7)
