.TH btparser "1" "24 May 2010" ""
.SH NAME
btparser \- a backtrace analyzer
.SH SYNOPSIS
.B btparser
[option]... [FILE]
.SH DESCRIPTION
.I btparser
is a command line tool that analyzes backtraces produced by
GDB and provides their textual representation useful for
crash duplication detection.

By default, btparser prints the backtrace tree created by
parsing the input file.

.SH OPTIONS
.B Basic startup options
.IP "\-V, \-\-version"
Displays version of btparser.
.IP "\-?, \-\-help"
Print a help message describing all of btparser’s command-line options.

.PP
.B Actions
.IP "\-r, \-\-rate"
Print a float number between 0 and 1, representing the quality of the
backtrace.
.IP "\-c, \-\-crash\-function"
Print the name of the function where the program crashed, if it's
successfully detected.
.IP "\-h, \-\-duplicate\-hash"
Print a short, textual representation of the backtrace, useful for
detecting the backtrace duplicates.

.PP
.B Additional options
.IP "\-d, \-\-debug"
Prints debug information when scanning/parsing the backtrace.
.IP "\-v, \-\-verbose"
Print more output than usual.
