.TH abrtd "8" "28 May 2009" ""
.SH NAME
abrtd \- automated bug reporting tool's daemon
.SH SYNOPSIS
.B abrtd [-dsv[v]...]
.SH DESCRIPTION
.I abrtd
is a daemon that watches for application crashes. When a crash occurs,
it collects the problem data (core file, application's command line etc.)
and takes action according to the type of application that
crashed and according to the configuration in the
.I abrt.conf
config file. There are plugins for various actions: for example to report
the crash to Bugzilla, to mail the report, or to transfer the
report via FTP or SCP. See the manual pages for the
respective plugins.
.SH OPTIONS

.TP
.B "\-d"

Stay in the foreground and log to standard error.
.TP
.B "\-s"

Log to system log even with option -d.
.TP
.B "\-v"

Log more detailed debugging information.
.SH CAVEATS
When you use some other crash-catching tool specific for an application
or an application type (for example BugBuddy for GNOME applications),
crashes of this type will be handled by that tool and
not by \fIabrtd\fP. If you want \fIabrtd\fP to handle these crashes,
turn off the higher-level crash-catching tool.
.SH "SEE ALSO"
.IR abrt.conf (5),
.IR abrt-plugins (7)
.SH AUTHOR
Written by Zdeněk Přikryl <zprikryl@redhat.com> and
Jiří Moskovčák <jmoskovc@redhat.com>. Manual page written by Daniel
Novotný <dnovotny@redhat.com>.
