.TH "abrt.conf" "5" "28 May 2009" ""
.SH NAME
abrt.conf \- configuration file for abrt
.SH DESCRIPTION
.P
.I abrt
is a daemon that watches for application crashes. When a crash occurs,
it collects the crash data and takes action according to
its configuration. This manual page describes \fIabrt\fP's configuration
file.
.P
The configuration file consists of sections, each section contains
several items in the format "Option = Value". A description of each
section follows:
.SS [Common]
.TP
.B EnableOpenGPG =  \fIyes\fP | \fIno\fP
When set to "yes",
.I abrt
will report crashes only in GPG signed packages. When set to "no",
it will report crashes also in unsigned packages. The default is "no".
.TP
.B OpenGPGPublicKeys =  \fIfilename\fP , \fIfilename\fP ...
These are the trusted GPG keys with which packages have to be
signed for
.I abrt
to report them if "EnableOpenGPG = yes".
.TP
.B BlackList = \fIpackageName\fP, \fIpackageName\fP ...
.I abrt
will ignore packages in this list and will not handle their crashes.
.TP
.B Database = \fIdatabasePlugin\fP
This specifies which database plugin
.I abrt
uses to store metadata about the crash.
.TP
.B MaxCrashReportsSize = \fInumber\fP
The maximum disk space (specified in megabytes) that
.I abrt
will use for all the crash dumps. Specify a value here to ensure
that the crash dumps will not fill all available storage space.
The default is 1000.
.TP
.B ActionsAndReporters = \fIplugin\fP, \fIplugin(parameters)\fP
List of reporter and action plugins which will be
run at crash time.
.TP
.B ProcessUnpackaged =  \fIyes\fP | \fIno\fP
When set to "yes",
.I abrt
will catch all crashes in the system. When set to "no",
it will catch crashes only in Fedora packages.
The default is "no".

.SS [ AnalyzerActionsAndReporters ]
This section contains associations between analyzers and action
or reporter plugins.
.TP
.B CCpp = \fIplugin\fP
.I abrt
will use this plugin when a C/C++ program crashes.
You can specify a plugin for specific program, for example
.br
CCpp:bind = Mailx("[abrt] Bind crashed")
.br
The Mailx plugin will run when bind crashes, instead of the plugin specified for
all the C/C++ programs.
.TP
.B Kerneloops = \fIplugin\fP
This plugin will be used in the case of kernel crashes.
.SS [ Cron ]
This section specifies tasks that will be run at some specified time. You can specify
either a time of day in the format
.br
.B hh:mm = \fIplugin\fP
.br
or an interval
.br
.B ss = \fIplugin2\fP
.br
in this case, \fIplugin2\fP will be run every \fIss\fP seconds (this number
can be greater than 60).
.SH "SEE ALSO"
.IR abrt (8),
.IR abrt-plugins (7)
.SH AUTHOR
Written by Zdeněk Přikryl <zprikryl@redhat.com> and
Jiří Moskovčák <jmoskovc@redhat.com>. Manual page written by Daniel
Novotný <dnovotny@redhat.com>.
