.TH abrt "8" "28 May 2009" ""
.SH NAME
abrt \- an automated bug-reporting tool
.SH SYNOPSIS
.B abrt [ -d ]
.SH DESCRIPTION
.I abrt
is a daemon which watches for application crashes. When a crash occurs,
it collects the crash data (core file, application's command line etc.)
and performs some actions according to the type of application that
crashed and according to configuration in the
.I abrt.conf
config file. There are plugins for various actions: for example reporting
the crash to Bugzilla, mailing the report, transfering the
report via FTP or SCP. See the manual pages for the
respective plugins.
.SH OPTIONS

.TP

.B "\-d"

This option causes
.I abrt
to print some more debugging information, when the daemon is started.
.SH CAVEATS
When you use some other crash catching tool, specific for an aplication
or an application type (for example BugBuddy for GNOME applications),
the crashes of this type will be handled by this application and
not \fIabrt\fP. If you don't want this behavior, turn the higher-level crash
catching application off: the crashes will be handled by \fIabrt\fP then.
.SH "SEE ALSO"
.IR abrt.conf (5),
.IR abrt-plugins (7)
.SH AUTHOR
Written by Zdeněk Přikryl <zprikryl@redhat.com> and
Jiří Moskovčák <jmoskovc@redhat.com>. Manual page written by Daniel
Novotný <dnovotny@redhat.com>.
