.TH "abrt.conf" "5" "28 May 2009" ""
.SH NAME
abrt.conf \- configuration file for abrt
.SH DESCRIPTION
.P
.I abrt
is a daemon that watches for application crashes. When a crash occurs,
it collects the problem data and takes action according to
its configuration. This manual page describes \fIabrt\fP's configuration
file.
.P
The configuration file consists of items in the format "Option = Value".
A description of each item follows:
.TP
.B OpenGPGCheck =  \fIyes\fP | \fIno\fP
When set to "yes",
.I abrt
will report crashes only in GPG signed packages. When set to "no",
it will report crashes also in unsigned packages. The default is "no".
.TP
.B OpenGPGPublicKeys =  \fIfilename\fP, \fIfilename\fP ...
These are the trusted GPG keys with which packages have to be
signed for
.I abrt
to report them if "OpenGPGCheck = yes".
.TP
.B BlackList = \fIpackageName\fP, \fIpackageName\fP ...
.I abrt
will ignore packages in this list and will not handle their crashes.
.TP
.B BlackListedPaths = \fI/path/to/ignore/*\fP, \fI*/another/ignored/path*\fP ...
.I abrt
will ignore crashes in executables whose absolute path matches
one of specified patterns.
.TP
.B MaxCrashReportsSize = \fInumber\fP
The maximum disk space (specified in megabytes) that
.I abrt
will use for all the crash dumps. Specify a value here to ensure
that the crash dumps will not fill all available storage space.
The default is 1000.
.TP
.B ProcessUnpackaged =  \fIyes\fP | \fIno\fP
When set to "yes",
.I abrt
will catch all crashes in the system. When set to "no",
it will catch crashes only in Fedora packages.
The default is "no".

.SH "SEE ALSO"
.IR abrtd (8),
.IR abrt-plugins (7)
.SH AUTHOR
Written by Zdeněk Přikryl <zprikryl@redhat.com> and
Jiří Moskovčák <jmoskovc@redhat.com>. Manual page written by Daniel
Novotný <dnovotny@redhat.com>.
