.TH "pyhook.conf" "5" "1 Oct 2009" ""
.SH NAME
pyhook.conf \- configuration file for abrt
.SH DESCRIPTION
.P
This configuration file controls whether python crash handler is enabled.
It has this format:
.TP
.B enabled =  \fIyes\fP | \fIno\fP
When set to "yes", crashing python programs will generate a crash report
for abrt. If not, they will not do that.
.SH "SEE ALSO"
.IR abrt (8),
.IR abrt-plugins (7)
.SH AUTHOR
Written by Jiří Moskovčák <jmoskovc@redhat.com>.
