#!/usr/bin/expect -f

spawn {*}$argv

set timeout 10
set identity 100

# timeout handler
proc itstime {args} {
    puts "!! expect timeout !!"
        exit 1
}

while {1} {
    expect {

        eof {
            break
        }

        timeout {
            itstime
        }

        -regexp {[[:space:]]+([[:digit:]]+)\.[[:space:]]+abrt-unprivileged} {
            set identity $expect_out(1,string)
        }

        "Choose identity to authenticate as" {
            send "$identity\n"
        }

        "Password:" {
            send "ribbit\n"
        }
    }
}

