#!/bin/bash

which nosetests-3 &> /dev/null
if [ $? -ne 0 ]; then
    echo 'python3-nose package required'
    exit 1
fi

export PYTHONPATH="problem/.libs/:$PYTHONPATH"
nosetests-3 --with-coverage --cover-package=problem --nocapture --no-skip --verbose tests/*.py
