#!/bin/bash

which nosetests &> /dev/null
if [ $? -ne 0 ]; then
    echo 'python-nose package required'
    exit 1
fi

export PYTHONPATH="problem/.libs/:$PYTHONPATH"
nosetests --with-coverage --cover-package=problem --nocapture --no-skip --verbose tests/*.py
