#!/bin/bash

##############################################################################
# Usage:                                                                     #
# abrt-retrace-worker retrace_directory                                      #
#                                                                            #
# retrace_directory is the directory created by abrt-retrace-interface.      #
# By default it is "/var/spool/abrt-retrace/crashid".                        #
#                                                                            #
# abrt-retrace-worker is a simple tool that runs worker.py (which contains   #
# the main part of retrace code), saves its output to the log and makes log  #
# and backtrace visible via abrt-retrace-interface.                          #
#                                                                            #
# Created by:                                                                #
# Michal Toman <mtoman@redhat.com>                                           #
##############################################################################

if [ $1 ] && [ ! $2 ] && [ -d "$1" ]
then
    export PYTHONPATH="/usr/share/abrt-retrace"
    LOG="$1/log"
    echo "Starting retrace" > $LOG
    exec /usr/bin/python /usr/share/abrt-retrace/worker.py "$1" >> $LOG
    RET=$?
    if [ $RET -eq "0" ]
    then
        echo "Retrace successful" >> $LOG
        mv "$1/backtrace" "$1/retrace_backtrace"
    else
        echo "Retrace failed" >> $LOG
    fi
    mv "$1/log" "$1/retrace_log"
    exit $RET
else
    echo "Usage: '$0 retrace_directory'"
    exit 127
fi
