.TH abrt "7" "1 Jun 2009" ""
.SH NAME
SQLite3 database plugin for abrt(8)
.SH DESCRIPTION
.P
.I abrt
is a daemon which watches for application crashes. When a crash occurs,
it collects the crash data and performs some actions according to 
the configuration. This manual page describes the \fISQLite3\fP database plugin 
for \fIabrt\fP.
.P
This is a database plugin: \fIabrt\fP needs some database to store
its metadata. You can choose which one, specifying "Database" in
the \fIabrt.conf\fP configuration file. Currently SQLite3 is
the only choice.
.SH INVOCATION
The plugin is invoked in the \fIabrt.conf\fP configuration file, like
this:
.br
[common]
.br
Database = SQLite3
.SH CONFIGURATION
The \fISQLite3.conf\fP configuration file contains one entry:
.SS DBPath
The path to the database.
.SH EXAMPLES
see \fBINVOCATION\fP
.SH "SEE ALSO"
.IR abrt (8),
.IR abrt.conf (5),
.IR abrt-plugins (7)
.SH AUTHOR
Written by Zdenek Prikryl <zprikryl@redhat.com> and Jiri
Moskovcak <jmoskovc@redhat.com>. Manual
page by Daniel Novotny <dnovotny@redhat.com>.
