.TH abrt "7" "1 Jun 2009" ""
.SH NAME
FileTransfer plugin for abrt(8)
.SH DESCRIPTION
.P
.I abrt
is a daemon that watches for application crashes. When a crash occurs,
it collects the crash data and takes action according to
its configuration. This manual page describes the \fIFileTransfer\fP plugin
for \fIabrt\fP.
.P
This plugin is used to transfer the crash report to another
machine using a file transfer protocol. The protocols supported
are FTP, FTPS, HTTP, HTTPS, SCP, SFTP, and TFTP.
.SH INVOCATION
.P
The plugin is invoked in the \fIabrt.conf\fP file, usually in the
\fIActionsAndReporters\fP option and/or the \fI[cron]\fP section.
There are two modes of invocation:
.P
* Specify \fIFileTransfer(one)\fP in ActionsAndReporters directive.
Immediately after crash is detected, the plugin transfers crash data
to the server specified in the \fIFileTransfer.conf\fP configuration file.
.P
* Specify \fIFileTransfer(store)\fP in ActionsAndReporters directive
and add \fIHH:MM = FileTransfer\fP line in [cron] section.
At the time of the crash,
the plugin stores a record of it in its internal list.
When specified time is reached, the plugin iterates through
its internal list and sends every recorded crash to the specified URL.
After that, the internal list is cleared.
.SH CONFIGURATION
The \fIFileTransfer.conf\fP configuration file contains
several entries in the format "Option = Value". The options are:
.SS URL
The URL of the server, where the crash should
be transfered, specifying the protocol, the path,
the user name and the password, for example:
.br
URL = ftp://user:passwd@server.com/path
.SS ArchiveType
The type of the archive in which to pack the crash data.
Currently, \fI.tar\fP, \fI.tar.gz\fP, \fI.tar.bz2\fP and \fI.zip\fP
are supported. The default is \fI.tar.gz\fP
.SS RetryCount
This specifies how many times the plugin will try to resend
the file if the transfer was not succesful. The plugin
waits a while before it retries the transfer: see \fIRetryDelay\fP.
The default is 3
.SS RetryDelay
If the transfer was not succesful, the plugin will
wait some time before sending the file again. This configuration
option specifies the time in seconds. The default is 20.
.SH EXAMPLES
.P
Typical configuration in \fIabrt.conf\fP. The crash is stored
each time it happens and at midnight, all the crash data
is transferred to a central server.
.P
[common]
.br
ActionsAndReporters = FileTransfer(store)
.br
[cron]
.br
00:00 = FileTransfer
.SH "SEE ALSO"
.IR abrt (8),
.IR abrt.conf (5),
.IR abrt-plugins (7)
.SH AUTHOR
Written by Daniel Novotny <dnovotny@redhat.com>.
