.TH abrt "7" "1 Jun 2009" ""
.SH NAME
KerneloopsScanner plugin for abrt(8)
.SH DESCRIPTION
.P
.I abrt
is a daemon which watches for application crashes. When a crash occurs,
it collects the crash data and performs some actions according to 
the configuration. This manual page describes the \fIKerneloopsScanner\fP 
plugin for \fIabrt\fP.
.P
This plugin reads the system log file (default /var/log/messages)
and stores the kernel oops crashes, which were not already
reported, to the abrt's debug dump directory.
.P
In order to distinguish between new crashes and the crashes
that were already reported, the plugin makes its own entry
in the log file, which acts as a separator.
.SH INVOCATION
The plugin is invoked in the \fIabrt.conf\fP configuration file. 
No parameters are necessary.
.SH CONFIGURATION
The \fIKerneloopsScanner.conf\fP configuration file contains one entry:
.SS SysLogFile
The file to scan. The default is 
.br
SysLogFile = /var/log/messages
.SH EXAMPLES
.P
This is a snippet from the \fIabrt.conf\fP configuration file.
Every 10 seconds look if there were any kernel crashes:
.P
[common]
.br
ActionsAndReporters = Kerneloops, KerneloopsScanner
.br
[cron]
.br
10 = KerneloopsScanner
.SH "SEE ALSO"
.IR abrt (8),
.IR abrt.conf (5),
.IR abrt-plugins (7)
.SH AUTHOR
Written by Anton Arapov <anton@redhat.com>. Manual
page by Daniel Novotny <dnovotny@redhat.com>.
