#!/bin/bash
# -*- mode: bash -*-

PASS=0
FAIL=0
for file in *.bt
do
  #echo "$file"
  ./abrt-backtrace $file &> /dev/null
  if [ "$?" -eq "0" ]
  then
      echo -n "."
      PASS=$(($PASS+1))
  else
      echo "-$file"
      FAIL=$(($FAIL+1))
  fi
done 