#!/usr/bin/expect

spawn {*}$argv

set timeout 10

# timeout handler
proc itstime {args} {
    puts "!! expect timeout !!"
    exit 1
}

while {1} {
    expect {

        eof {break}

        timeout { itstime }

        "Please enter user name for" {
            send "\n"
        }
    }
}

