#!/usr/bin/expect

spawn {*}$argv

set timeout 10
set event_no 4

# timeout handler
proc itstime {args} {
    puts "!! expect timeout !!"
    exit 1
}

while {1} {
    expect {

        eof {break}

        timeout { itstime }

        -regexp {[[:space:]]+([[:digit:]]+)\)[[:space:]]+Report uploader} {
            set event_no $expect_out(1,string)
        }

        "Please enter user name for" {
            send "\n"
        }
        "Select reporter(s)" {
            send "$event_no\n"
        }
    }
}

