#!/bin/sh

exec rpmbuild \
--define "_topdir $PWD" \
--define "_builddir $PWD" \
--define "_rpmdir $PWD" \
--define "_sourcedir $PWD" \
--define "_specdir $PWD" \
--define "_srcrpmdir $PWD" \
--define "_build_name_fmt %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm" \
"$@"
