.TH abrt "8" "28 May 2009" ""
.SH NAME
abrt-plugins \- plugins for the abrt crash reporter program
.SH DESCRIPTION
.P
.I abrt
is a daemon that watches for application crashes. When a crash occurs,
it collects the problem data (core file, application's command line etc.)
and takes action according to the type of application that
crashed and according to the configuration specified in the
.I abrt.conf
configuration file.
.P
Plugins allow abrt to perform various actions: for example,
to report the crash to Bugzilla, to mail the report, to transfer
the report via FTP or SCP, or to run a program that you specify.
.P
This manual page provides a list of all the manual pages for
these plugins.
.P
If you want to create your own plugin, refer to the PLUGINS-HOWTO
file in the documentation directory.
.SH INVOCATION
Each plugin is invoked in the \fIabrt.conf\fP configuration
file, in the section that is appropriate to what you
want abrt to do.
.SH CONFIGURATION
Almost every plugin has its configuration file,
stored in the \fI/etc/abrt/plugins\fP directory.
.SH "SEE ALSO"
.IR abrt (8),
.IR abrt.conf (5),
.IR abrt-Bugzilla (7),
.IR abrt-Upload (7),
.IR abrt-KerneloopsReporter (7),
.IR abrt-Logger (7),
.IR abrt-Mailx (7),
.SH AUTHOR
\fIabrt\fP written by Zdeněk Přikryl <zprikryl@redhat.com> and
Jiří Moskovčák <jmoskovc@redhat.com>. Manual page written by Daniel
Novotný <dnovotny@redhat.com>.
