.TH abrt "7" "1 Jun 2009" ""
.SH NAME
Mailx plugin for abrt(8)
.SH DESCRIPTION
.P
.I abrt
is a daemon that watches for application crashes. When a crash occurs,
it collects the problem data and takes action according to
its configuration. This manual page describes the \fIMailx\fP plugin
for \fIabrt\fP.
.P
This plugin is used to mail the data about the crash
to a specified mail address.
.SH INVOCATION
The plugin is invoked in the \fIabrt.conf\fP configuration file. It can take
one parameter, a subject of the mail (if it differs from the
one specified in the \fIMailx.conf\fP configuration file).
.SH CONFIGURATION
The \fIMailx.conf\fP configuration file contains
several entries in a format "Option = Value". The options are:
.SS Subject
The subject of the mail.
.SS Parameters
The \fIMailx\fP plugin executes the external "mailx" command to
send the mail. This option defines some additional command line
parameters, which should be added to the program invocation, if any.
.SS EmailFrom
The address from which the email is sent.
.SS EmailTo
The address to which the email is sent.
.SS SendBinaryData
Can be "yes" or "no". If set to "yes", the email will also
contain the binary files associated with the crash. Warning:
this can cause the emails to be large! (several MB)
.SH EXAMPLES
.P
These are snippets from the \fIabrt.conf\fP configuration file.
.P
1) Each time a crash happens, a mail is sent
.PP
[common]
.br
ActionsAndReporters = Mailx("[abrt] a crash occurs")
.P
2) When a program in a specific package (in this case "httpd") crashes,
send a mail about it.
.PP
[AnalyzerActionsAndReporters]
.br
CCpp:httpd = Mailx("[abrt] Apache crash")
.SH "SEE ALSO"
.IR abrt (8),
.IR abrt.conf (5),
.IR abrt-plugins (7)
.SH AUTHOR
Written by Zdenek Prikryl <zprikryl@redhat.com>. Manual
page by Daniel Novotny <dnovotny@redhat.com>.
