.TH abrt "7" "1 Jun 2009" ""
.SH NAME
Bugzilla plugin for abrt(8)
.SH DESCRIPTION
.P
.I abrt
is a daemon that watches for application crashes. When a crash occurs,
it collects the problem data and takes action according to
its configuration. This manual page describes the \fIBugzilla\fP plugin
for \fIabrt\fP.
.P
This plugin is used to report the crash to a Bugzilla instance. The
plugin will determine the package name and distribution version. The
problem data is attached to the bug report.
.SH INVOCATION
The plugin is invoked in the \fIabrt.conf\fP configuration file.
No parameters are necessary.
.SH CONFIGURATION
The \fIBugzilla.conf\fP configuration file contains several
entries in the format "Option = Value". The options are:
.SS BugzillaURL
The URL of the Bugzilla instance that you want to use, including the
path to the xmlrpc. The default is https://bugzilla.redhat.com/xmlrpc.cgi
.SS Login
Your Bugzilla login. If you have no Bugzilla account, you cannot
use the plugin.
.SS Password
Your Bugzilla password.
.SH EXAMPLES
.P
This is a snippet from the \fIabrt.conf\fP configuration file.
When something crashes, use the Bugzilla plugin:
.P
[common]
.br
ActionsAndReporters = Bugzilla
.SH "SEE ALSO"
.IR abrt (8),
.IR abrt.conf (5),
.IR abrt-plugins (7)
.SH AUTHOR
Written by Zdenek Prikryl <zprikryl@redhat.com>.
Manual page written by Daniel Novotny <dnovotny@redhat.com>.
