#!/bin/sh
#
# This script is meant to be run once at system startup after abrtd is up and running.
# It moves all vmcore directories in /var/crash (which are presumably created by kdump)
# to abrtd spool directory.
#
# The goal is to let abrtd notice and process them as new problem data dirs.
#

cd /var/crash || exit 0

for d in *; do
	test -d "$d" || continue
	test -f "$d/vmcore" || continue
	# Let abrtd know what type of problem it is:
	printf "vmcore" >"$d/analyzer"
	# Move to abrt spool dir.
	# We use .new suffix - mv might use copy+delete to do
	# the move: we must make sure abrtd doesn't try to process
	# partially-copied directory.
	mv -- "$d" "/var/spool/abrt/vmcore-$d.new" || continue
	mv -- "/var/spool/abrt/vmcore-$d.new" "/var/spool/abrt/vmcore-$d"
done
