#!/usr/bin/expect -f

set action [lindex $argv 0]
set args [lrange $argv 1 end]

spawn -noecho sh -c "abrt-cli $args && sleep 0.5"

set timeout 10

# timeout handler
proc itstime {args} {
    puts "!! expect timeout !!"
        exit 1
}

while {1} {
    expect {

        eof {break}

        timeout { itstime }

        -re {([[:digit:]]+)(?= Report testing)} {
            send "$expect_out(0,string)\n"
        }

        "Actions: remove(rm), report(e), info(i), skip(s):" {
            send "$action\n"
        }
        "Actions: remove(rm), info(i), skip(s):" {
            send "$action\n"
        }
       "For next problem press ENTER:" {
            send "\n"
        }
    }
}

